[package]
name = "turbofieldfare-openai-api"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
futures-util.workspace = true
openai-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
turbofieldfare-protocol = { path = "../protocol" }
uuid.workspace = true

[dev-dependencies]
tower.workspace = true

[lints]
workspace = true
